import {
  Activity,
  Building2,
  Boxes,
  ContactRound,
  CreditCard,
  FileText,
  Filter,
  Gauge,
  Headphones,
  KanbanSquare,
  ListChecks,
  ListTodo,
  MessageSquare,
  Palette,
  Tags,
  ReceiptText,
  Settings,
  Radio,
  Bell,
  Route,
  UsersRound
} from 'lucide-react';

export const sidebarItemsByRole = {
  SUPERADMIN: [
    { label: 'Resumen', icon: Gauge, to: '/superadmin' },
    { label: 'Distribuidores', icon: Building2, to: '/superadmin/distributors' },
    { label: 'Planes plataforma', icon: CreditCard, to: '/superadmin/platform-plans' },
    { label: 'Suscripciones', icon: ReceiptText, to: '/superadmin/subscriptions' },
    { label: 'Billing', icon: FileText, to: '/superadmin/billing' },
    { label: 'Modulos', icon: Boxes, to: '/superadmin/modules' },
    { label: 'Auditoria', icon: Activity, to: '/superadmin/audit' }
  ],
  DISTRIBUTOR: [
    { label: 'Dashboard', icon: Gauge, to: '/distributor/dashboard' },
    { label: 'Planes', icon: CreditCard, to: '/distributor/dashboard#planes' },
    { label: 'Empresas', icon: Building2, to: '/distributor/companies' },
    { label: 'Crear admin', icon: UsersRound, to: '/distributor/dashboard#admins' },
    { label: 'Suscripciones', icon: CreditCard, to: '/distributor/dashboard#suscripciones' },
    { label: 'Finanzas', icon: Gauge, to: '/distributor/finance' },
    { label: 'Facturas', icon: FileText, to: '/distributor/invoices' },
    { label: 'Pagos', icon: ReceiptText, to: '/distributor/payments' },
    { label: 'Branding', icon: Palette, to: '/distributor/branding' },
    { label: 'Configuracion', icon: Settings, to: '/distributor/settings' },
    { label: 'Onboarding', icon: ListChecks, to: '/distributor/onboarding' },
    { label: 'Mi plataforma', icon: ReceiptText, to: '/distributor/dashboard#plataforma' }
  ],
  ADMIN: [
    { label: 'Dashboard', icon: Gauge, to: '/admin/dashboard' },
    { label: 'Inbox', icon: MessageSquare, to: '/inbox' },
    { label: 'Canales', icon: Radio, to: '/inbox/channels' },
    { label: 'Plantillas', icon: FileText, to: '/inbox/templates' },
    { label: 'Routing', icon: Route, to: '/inbox/routing' },
    { label: 'Notificaciones', icon: Bell, to: '/notifications' },
    { label: 'CRM', icon: Activity, to: '/crm' },
    { label: 'Contactos', icon: ContactRound, to: '/crm/contacts' },
    { label: 'Oportunidades', icon: CreditCard, to: '/crm/opportunities' },
    { label: 'Pipeline', icon: KanbanSquare, to: '/crm/pipeline' },
    { label: 'Tareas', icon: ListTodo, to: '/crm/tasks' },
    { label: 'Tags', icon: Tags, to: '/crm/tags' },
    { label: 'Campos personalizados', icon: ListChecks, to: '/crm/custom-fields' },
    { label: 'Segmentos', icon: Filter, to: '/crm/segments' },
    { label: 'Configurar pipelines', icon: Settings, to: '/crm/pipelines' },
    { label: 'Importar contactos', icon: FileText, to: '/crm/import' },
    { label: 'Usuarios internos', icon: UsersRound, to: '/admin/dashboard#usuarios' },
    { label: 'Contactos', icon: ContactRound, to: '/admin/dashboard#contactos' },
    { label: 'Actividad', icon: Activity, to: '/admin/dashboard#actividad' },
    { label: 'Plan contratado', icon: CreditCard, to: '/admin/dashboard#plan' },
    { label: 'Facturacion', icon: FileText, to: '/admin/dashboard#facturacion' },
    { label: 'Configuracion', icon: Settings, to: '/admin/dashboard#configuracion' },
    { label: 'Onboarding', icon: ListChecks, to: '/admin/dashboard#onboarding' }
  ],
  SUPERVISOR: [
    { label: 'Supervision', icon: Gauge, to: '/supervisor/dashboard' },
    { label: 'Inbox del equipo', icon: MessageSquare, to: '/inbox' },
    { label: 'Notificaciones', icon: Bell, to: '/notifications' },
    { label: 'CRM del equipo', icon: Activity, to: '/crm' },
    { label: 'Contactos del equipo', icon: ContactRound, to: '/crm/contacts' },
    { label: 'Pipeline del equipo', icon: KanbanSquare, to: '/crm/pipeline' },
    { label: 'Oportunidades', icon: CreditCard, to: '/crm/opportunities' },
    { label: 'Tareas', icon: ListTodo, to: '/crm/tasks' },
    { label: 'Segmentos', icon: Filter, to: '/crm/segments' },
    { label: 'Agentes', icon: Headphones, to: '/supervisor/dashboard#agentes' },
    { label: 'Contactos', icon: ContactRound, to: '/supervisor/dashboard#contactos' },
    { label: 'Actividad', icon: Activity, to: '/supervisor/dashboard#actividad' },
    { label: 'Metricas', icon: UsersRound, to: '/supervisor/dashboard#metricas' }
  ],
  CALLCENTER: [
    { label: 'Mi dashboard', icon: Gauge, to: '/callcenter/dashboard' },
    { label: 'Mi inbox', icon: MessageSquare, to: '/inbox' },
    { label: 'Notificaciones', icon: Bell, to: '/notifications' },
    { label: 'Mi CRM', icon: Activity, to: '/crm' },
    { label: 'Mis contactos', icon: ContactRound, to: '/crm/contacts' },
    { label: 'Mis oportunidades', icon: CreditCard, to: '/crm/opportunities' },
    { label: 'Mis tareas', icon: ListTodo, to: '/crm/tasks' },
    { label: 'Seguimientos', icon: KanbanSquare, to: '/crm/contacts?followUp=today' },
    { label: 'Contactos', icon: ContactRound, to: '/callcenter/dashboard#contactos' },
    { label: 'Gestion', icon: Headphones, to: '/callcenter/dashboard#gestion-contacto' },
    { label: 'Actividad', icon: Activity, to: '/callcenter/dashboard#actividad' }
  ]
};
