import mongoose from 'mongoose';

const activityLogSchema = new mongoose.Schema(
  {
    companyId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Company',
      default: null
    },
    distributorId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Distributor',
      default: null
    },
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true
    },
    type: {
      type: String,
      enum: [
        'call',
        'message',
        'note',
        'login',
        'company_created',
        'company_updated',
        'company_suspended',
        'company_reactivated',
        'plan_created',
        'plan_updated',
        'subscription_created',
        'subscription_updated',
        'user_created',
        'contact_created',
        'contact_updated',
        'contact_deleted',
        'contact_assigned',
        'status_change',
        'note_added',
        'follow_up_updated',
        'distributor_created',
        'distributor_updated',
        'distributor_suspended',
        'distributor_reactivated',
        'platform_plan_created',
        'platform_plan_updated',
        'platform_subscription_created',
        'platform_subscription_updated',
        'invoice_created',
        'invoice_updated',
        'payment_recorded',
        'company_invoice_created',
        'company_invoice_updated',
        'company_payment_recorded',
        'distributor_settings_updated',
        'distributor_branding_updated',
        'onboarding_updated',
        'module_entitlement_updated',
        'impersonation_started',
        'impersonation_ended',
        'contact_imported',
        'contact_exported',
        'contact_tags_updated',
        'tag_created',
        'tag_updated',
        'tag_deleted',
        'custom_field_created',
        'custom_field_updated',
        'custom_field_deleted',
        'segment_created',
        'segment_updated',
        'pipeline_created',
        'pipeline_updated',
        'pipeline_stage_created',
        'pipeline_stage_updated',
        'pipeline_stage_reordered',
        'opportunity_created',
        'opportunity_updated',
        'opportunity_stage_changed',
        'opportunity_won',
        'opportunity_lost',
        'opportunity_archived',
        'task_created',
        'task_updated',
        'task_completed',
        'task_archived',
        'crm_note_created',
        'conversation_created',
        'conversation_assigned',
        'conversation_closed',
        'conversation_reopened',
        'conversation_archived',
        'conversation_read',
        'message_inbound_received',
        'message_outbound_created',
        'message_outbound_sent',
        'message_outbound_failed',
        'conversation_internal_note_created',
        'channel_configured',
        'channel_config_updated',
        'channel_disabled',
        'webhook_received',
        'webhook_processed',
        'webhook_failed',
        'message_template_created',
        'message_template_updated',
        'message_template_disabled',
        'contact_created_from_inbound'
      ],
      required: true
    },
    summary: {
      type: String,
      required: true
    },
    metadata: {
      type: mongoose.Schema.Types.Mixed,
      default: {}
    }
  },
  { timestamps: true }
);

export const ActivityLog = mongoose.model('ActivityLog', activityLogSchema);
