import mongoose from 'mongoose';
import { sanitize } from '../utils/sanitize.js';

const activityLogSchema = new mongoose.Schema(
  {
    companyId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Company',
      default: null
    },
    distributorId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Distributor',
      default: null
    },
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true
    },
    type: {
      type: String,
      enum: [
        'call',
        'message',
        'note',
        'login',
        'company_created',
        'company_updated',
        'company_suspended',
        'company_reactivated',
        'plan_created',
        'plan_updated',
        'subscription_created',
        'subscription_updated',
        'user_created',
        'contact_created',
        'contact_updated',
        'contact_deleted',
        'contact_assigned',
        'status_change',
        'note_added',
        'follow_up_updated',
        'distributor_created',
        'distributor_updated',
        'distributor_suspended',
        'distributor_reactivated',
        'platform_plan_created',
        'platform_plan_updated',
        'platform_subscription_created',
        'platform_subscription_updated',
        'invoice_created',
        'invoice_updated',
        'payment_recorded',
        'company_invoice_created',
        'company_invoice_updated',
        'company_payment_recorded',
        'distributor_settings_updated',
        'distributor_branding_updated',
        'onboarding_updated',
        'module_entitlement_updated',
        'impersonation_started',
        'impersonation_ended',
        'permissions_updated',
        'permission_template_applied',
        'user_role_changed',
        'contact_imported',
        'contact_exported',
        'contact_tags_updated',
        'crm_bulk_action',
        'tag_created',
        'tag_updated',
        'tag_deleted',
        'custom_field_created',
        'custom_field_updated',
        'custom_field_deleted',
        'segment_created',
        'segment_updated',
        'pipeline_created',
        'pipeline_updated',
        'pipeline_stage_created',
        'pipeline_stage_updated',
        'pipeline_stage_reordered',
        'opportunity_created',
        'opportunity_updated',
        'opportunity_stage_changed',
        'opportunity_won',
        'opportunity_lost',
        'opportunity_archived',
        'task_created',
        'task_updated',
        'task_completed',
        'task_archived',
        'crm_note_created',
        'conversation_created',
        'conversation_assigned',
        'conversation_closed',
        'conversation_reopened',
        'conversation_archived',
        'conversation_read',
        'message_inbound_received',
        'message_outbound_created',
        'message_outbound_sent',
        'message_outbound_failed',
        'message_outbound_blocked',
        'message_outbound_scheduled',
        'consent_updated',
        'consent_revoked',
        'global_dnd_updated',
        'communication_preferences_updated',
        'suppression_created',
        'suppression_revoked',
        'quiet_hours_updated',
        'opt_out_detected',
        'consent_override_applied',
        'conversation_internal_note_created',
        'channel_configured',
        'channel_config_updated',
        'channel_disabled',
        'channel_default_changed',
        'channel_quality_changed',
        'webhook_received',
        'webhook_processed',
        'webhook_failed',
        'message_template_created',
        'message_template_updated',
        'message_template_disabled',
        'message_template_registered',
        'message_template_synced',
        'contact_created_from_inbound',
        'routing_rule_created',
        'routing_rule_updated',
        'routing_rule_toggled',
        'media_stored',
        'media_downloaded',
        'media_upload_created',
        'message_status_updated',
        'job_replayed',
        'operational_alert_acknowledged',
        'channel_secret_rotated',
        'whatsapp_session_created',
        'whatsapp_session_connect_requested',
        'whatsapp_session_reconnect_requested',
        'whatsapp_session_qr_regenerated',
        'whatsapp_session_disconnected',
        'whatsapp_session_auth_deleted',
        'whatsapp_session_enabled_updated',
        'calendar_created',
        'calendar_updated',
        'calendar_archived',
        'calendar_profile_applied',
        'availability_rule_created',
        'availability_rule_updated',
        'availability_rule_deleted',
        'availability_exception_created',
        'availability_exception_updated',
        'availability_exception_deleted',
        'booking_link_created',
        'booking_link_updated',
        'booking_link_archived',
        'appointment_created',
        'appointment_updated',
        'appointment_confirmed',
        'appointment_cancelled',
        'appointment_completed',
        'appointment_no_show',
        'appointment_rescheduled',
        'appointment_reminder_sent',
        'workflow_created',
        'workflow_updated',
        'workflow_activated',
        'workflow_paused',
        'workflow_archived',
        'workflow_tested',
        'workflow_activity_created',
        'form_created',
        'form_updated',
        'form_published',
        'form_paused',
        'form_archived',
        'form_submitted',
        'form_submission_processed',
        'form_spam_detected',
        'contact_created_from_form',
        'opportunity_created_from_form',
        'landing_page_created',
        'landing_page_updated',
        'landing_page_published',
        'landing_page_paused',
        'landing_page_archived',
        'funnel_created',
        'funnel_updated',
        'funnel_published',
        'funnel_paused',
        'funnel_archived',
        'funnel_step_created',
        'funnel_step_updated',
        'funnel_step_published',
        'funnel_step_archived',
        'conversion_recorded',
        'campaign_created',
        'campaign_updated',
        'integration_created',
        'integration_updated',
        'review_request_created',
        'review_request_cancelled',
        'review_request_completed',
        'review_received',
        'review_approved',
        'review_rejected',
        'review_published',
        'review_archived',
        'review_responded',
        'testimonial_created',
        'testimonial_published',
        'testimonial_archived',
        'review_widget_created',
        'review_widget_published',
        'review_widget_archived',
        'satisfaction_survey_created',
        'satisfaction_survey_published',
        'satisfaction_survey_paused',
        'satisfaction_survey_archived',
        'survey_response_received',
        'coupon_created',
        'coupon_issued',
        'coupon_redeemed',
        'coupon_redemption_cancelled',
        'referral_program_created',
        'referral_program_activated',
        'referral_program_paused',
        'referral_program_archived',
        'referral_created',
        'referral_converted',
        'referral_rewarded'
      ],
      required: true
    },
    summary: {
      type: String,
      required: true
    },
    metadata: {
      type: mongoose.Schema.Types.Mixed,
      default: {}
    }
  },
  { timestamps: true }
);

activityLogSchema.pre('validate', function sanitizeMetadata(next) {
  this.summary = sanitize(this.summary);
  this.metadata = sanitize(this.metadata || {});
  next();
});

export const ActivityLog = mongoose.model('ActivityLog', activityLogSchema);
