export const ROLE_PERMISSIONS = {
  SUPERADMIN: [
    'platform:manage',
    'distributors:manage',
    'platform_plans:manage',
    'platform_subscriptions:manage',
    'platform_billing:manage',
    'modules:manage',
    'impersonation:manage',
    'audit:read_all',
    'ops:read_all',
    'jobs:read_all',
    'jobs:replay_all',
    'alerts:read_all',
    'alerts:ack_all',
    'workflows:read_all',
    'workflows:manage_all',
    'workflow_runs:read_all',
    'forms:read_all',
    'landing_pages:read_all',
    'funnels:read_all',
    'campaigns:read_all',
    'integrations:read_all',
    'marketing_reports:read_all',
    'attribution:read_all',
    'reputation:read_all'
  ],
  DISTRIBUTOR: [
    'companies:manage',
    'distributor_plans:manage',
    'company_subscriptions:manage',
    'distributor_billing:read',
    'distributor_billing:manage',
    'company_invoices:manage',
    'company_payments:manage',
    'distributor_settings:manage',
    'distributor_branding:manage',
    'companies:suspend',
    'modules:read',
    'impersonation:start_admin',
    'activity:read_distributor',
    'campaigns:read_distributor',
    'campaigns:manage_distributor',
    'integrations:read_distributor',
    'integrations:manage_distributor'
  ],
  ADMIN: [
    'users:manage',
    'crm:manage',
    'contacts:manage',
    'contacts:assign',
    'contacts:import',
    'contacts:export',
    'tags:manage',
    'custom_fields:manage',
    'segments:manage',
    'pipelines:manage',
    'opportunities:manage',
    'tasks:manage',
    'notes:manage',
    'conversations:manage',
    'conversations:read',
    'conversations:assign',
    'conversations:send',
    'conversations:close',
    'channel_configs:manage',
    'message_templates:manage',
    'activity:read',
    'company_billing:read',
    'company_settings:read',
    'company_onboarding:update',
    'notifications:read',
    'routing_rules:manage',
    'ops:read_company',
    'jobs:read_company',
    'jobs:replay_company',
    'alerts:read_company',
    'alerts:ack_company',
    'media:read',
    'media:upload',
    'channel_diagnostics:read',
    'channel_secrets:rotate',
    'consent:read',
    'consent:manage',
    'consent:override',
    'consent:export',
    'dnd:read',
    'dnd:manage',
    'suppressions:manage',
    'quiet_hours:manage',
    'message_diagnostics:read',
    'messages:send_commercial',
    'messages:send_transactional',
    'communication_reports:read',
    'calendars:manage',
    'appointments:manage',
    'appointment_analytics:read',
    'booking_links:manage',
    'availability:manage',
    'calendar_profiles:apply',
    'workflows:read',
    'workflows:manage',
    'workflows:test',
    'workflow_runs:read',
    'forms:manage',
    'forms:read',
    'forms:submissions',
    'forms:analytics',
    'landing_pages:manage',
    'landing_pages:analytics',
    'funnels:manage',
    'funnels:analytics',
    'campaigns:manage',
    'campaigns:read',
    'integrations:manage',
    'integrations:read',
    'integrations:events',
    'attribution:read',
    'marketing_reports:read',
    'reputation:manage',
    'reviews:manage',
    'review_requests:manage',
    'testimonials:manage',
    'review_widgets:manage',
    'surveys:manage',
    'coupons:manage',
    'referrals:manage',
    'reputation:analytics'
  ],
  SUPERVISOR: [
    'crm:read_team',
    'contacts:read_team',
    'contacts:update_team',
    'contacts:assign_team',
    'opportunities:read_team',
    'opportunities:update_team',
    'opportunities:assign_team',
    'tasks:create_team',
    'tasks:update_team',
    'notes:create_team',
    'conversations:read_team',
    'conversations:assign_team',
    'conversations:send_team',
    'conversations:close_team',
    'message_templates:read',
    'activity:read_team',
    'users:read_team',
    'notifications:read',
    'routing_rules:read',
    'media:read_team',
    'media:upload_team',
    'consent:read_team',
    'consent:manage_team',
    'dnd:read_team',
    'dnd:manage_team',
    'message_diagnostics:read_team',
    'messages:send_commercial',
    'messages:send_transactional',
    'communication_reports:read_team',
    'calendars:read_team',
    'appointments:manage_team',
    'appointments:read_team',
    'appointments:update_team',
    'appointment_analytics:read_team',
    'availability:read_team',
    'workflows:read_team',
    'workflow_runs:read_team',
    'forms:read_team',
    'forms:submissions_read',
    'funnels:read_team',
    'campaigns:read_team',
    'integrations:read_team',
    'integrations:events',
    'attribution:read_team',
    'marketing_reports:read_team',
    'reviews:read_team',
    'review_requests:create_team',
    'coupons:issue_team',
    'referrals:read_team'
  ],
  CALLCENTER: [
    'contacts:read_assigned',
    'contacts:update_assigned',
    'contacts:notes',
    'contacts:followup',
    'opportunities:read_assigned',
    'opportunities:update_assigned',
    'tasks:read_assigned',
    'tasks:update_assigned',
    'notes:create_assigned',
    'followups:manage_assigned',
    'conversations:read_assigned',
    'conversations:send_assigned',
    'conversations:internal_notes',
    'message_templates:use',
    'notifications:read',
    'media:read_assigned',
    'media:upload_assigned',
    'consent:read_assigned',
    'consent:record_assigned',
    'dnd:read_assigned',
    'communication_preferences:update_assigned',
    'message_diagnostics:read_assigned',
    'messages:send_commercial',
    'messages:send_transactional',
    'calendars:read_assigned',
    'appointments:manage_assigned',
    'appointments:read_assigned',
    'appointments:update_assigned',
    'appointment_analytics:read_assigned',
    'review_requests:create_assigned',
    'coupons:issue_assigned',
    'reviews:read_assigned',
    'activity:read_self',
    'attribution:read_assigned'
  ]
};

export function hasPermission(role, permission) {
  return role === 'SUPERADMIN' || ROLE_PERMISSIONS[role]?.includes(permission) || false;
}

export function hasUserPermission(user, permission) {
  if (!user) return false;
  if (user.role === 'SUPERADMIN') return true;
  if (Array.isArray(user.permissions)) {
    if (hasPermission(user.role, permission) && user.permissions.includes(permission)) {
      return true;
    }
    const legacyFallbacks = {
      'consent:read': ['contacts:manage'],
      'consent:read_team': ['contacts:read_team'],
      'consent:read_assigned': ['contacts:read_assigned'],
      'consent:manage': ['contacts:manage'],
      'consent:override': ['conversations:manage'],
      'consent:export': ['contacts:export'],
      'consent:manage_team': ['contacts:update_team'],
      'consent:record_assigned': ['contacts:update_assigned'],
      'dnd:read': ['contacts:manage'],
      'dnd:read_team': ['contacts:read_team'],
      'dnd:read_assigned': ['contacts:read_assigned'],
      'dnd:manage': ['contacts:manage'],
      'suppressions:manage': ['channel_configs:manage'],
      'quiet_hours:manage': ['channel_configs:manage'],
      'dnd:manage_team': ['contacts:update_team'],
      'communication_preferences:update_assigned': ['contacts:update_assigned'],
      'message_diagnostics:read': ['conversations:read'],
      'message_diagnostics:read_team': ['conversations:read_team'],
      'message_diagnostics:read_assigned': ['conversations:read_assigned'],
      'messages:send_commercial': [
        'conversations:send',
        'conversations:send_team',
        'conversations:send_assigned'
      ],
      'messages:send_transactional': [
        'conversations:send',
        'conversations:send_team',
        'conversations:send_assigned'
      ],
      'communication_reports:read': ['marketing_reports:read'],
      'communication_reports:read_team': ['marketing_reports:read_team']
    };
    return Boolean(
      hasPermission(user.role, permission) &&
      legacyFallbacks[permission]?.some((legacy) => user.permissions.includes(legacy))
    );
  }
  return hasPermission(user.role, permission);
}
