import { ROLE_PERMISSIONS } from './permissions.js';

export const PERMISSION_TEMPLATES = [
  {
    key: 'admin_full',
    name: 'ADMIN completo',
    description: 'Referencia de acceso administrativo, limitada por los modulos del plan.',
    targetRoles: ['ADMIN'],
    permissions: ROLE_PERMISSIONS.ADMIN
  },
  {
    key: 'supervisor_commercial',
    name: 'Supervisor comercial',
    description: 'Gestion comercial del equipo sin facturacion ni configuracion global.',
    targetRoles: ['SUPERVISOR'],
    permissions: [
      'crm:read_team',
      'contacts:read_team',
      'contacts:update_team',
      'contacts:assign_team',
      'opportunities:read_team',
      'opportunities:update_team',
      'opportunities:assign_team',
      'tasks:create_team',
      'tasks:update_team',
      'notes:create_team',
      'conversations:read_team',
      'conversations:assign_team',
      'conversations:send_team',
      'conversations:close_team',
      'message_templates:read',
      'activity:read_team',
      'users:read_team',
      'notifications:read',
      'consent:read_team',
      'consent:manage_team',
      'dnd:read_team',
      'dnd:manage_team',
      'message_diagnostics:read_team',
      'messages:send_commercial',
      'messages:send_transactional',
      'communication_reports:read_team',
      'calendars:read_team',
      'appointments:manage_team',
      'appointments:read_team',
      'appointments:update_team',
      'appointment_analytics:read_team',
      'availability:read_team',
      'reviews:read_team',
      'review_requests:create_team'
    ]
  },
  {
    key: 'callcenter',
    name: 'Call center',
    description: 'Inbox, contactos, oportunidades, tareas, notas y citas asignadas.',
    targetRoles: ['CALLCENTER'],
    permissions: ROLE_PERMISSIONS.CALLCENTER
  },
  {
    key: 'support_service',
    name: 'Soporte / servicio al cliente',
    description: 'Atencion por inbox, notas y agenda disponible.',
    targetRoles: ['SUPERVISOR', 'CALLCENTER'],
    permissions: [
      'contacts:read_team',
      'contacts:update_team',
      'contacts:read_assigned',
      'contacts:update_assigned',
      'contacts:notes',
      'notes:create_team',
      'notes:create_assigned',
      'conversations:read_team',
      'conversations:assign_team',
      'conversations:send_team',
      'conversations:close_team',
      'conversations:read_assigned',
      'conversations:send_assigned',
      'conversations:internal_notes',
      'message_templates:read',
      'message_templates:use',
      'notifications:read',
      'consent:read_team',
      'dnd:read_team',
      'message_diagnostics:read_team',
      'messages:send_transactional',
      'consent:read_assigned',
      'consent:record_assigned',
      'dnd:read_assigned',
      'communication_preferences:update_assigned',
      'message_diagnostics:read_assigned',
      'messages:send_commercial',
      'messages:send_transactional',
      'activity:read_team',
      'calendars:read_team',
      'appointments:manage_team',
      'appointments:read_team',
      'appointments:update_team',
      'calendars:read_assigned',
      'appointments:manage_assigned',
      'appointments:read_assigned',
      'appointments:update_assigned'
    ]
  }
];

const PERMISSION_MODULES = {
  'company_billing:read': ['billing'],
  'distributor_billing:read': ['billing'],
  'distributor_billing:manage': ['billing'],
  'company_invoices:manage': ['billing'],
  'company_payments:manage': ['billing'],
  'crm:manage': ['crm'],
  'crm:read_team': ['crm'],
  'contacts:manage': ['crm', 'contacts'],
  'contacts:assign': ['crm', 'contacts'],
  'contacts:import': ['crm', 'contacts'],
  'contacts:export': ['crm', 'contacts'],
  'contacts:read_team': ['crm', 'contacts'],
  'contacts:update_team': ['crm', 'contacts'],
  'contacts:assign_team': ['crm', 'contacts'],
  'contacts:read_assigned': ['crm', 'contacts'],
  'contacts:update_assigned': ['crm', 'contacts'],
  'contacts:notes': ['crm', 'contacts'],
  'contacts:followup': ['crm', 'contacts'],
  'tags:manage': ['crm', 'contacts'],
  'custom_fields:manage': ['crm', 'contacts'],
  'segments:manage': ['crm', 'contacts'],
  'pipelines:manage': ['crm', 'opportunities'],
  'opportunities:manage': ['crm', 'opportunities'],
  'opportunities:read_team': ['crm', 'opportunities'],
  'opportunities:update_team': ['crm', 'opportunities'],
  'opportunities:assign_team': ['crm', 'opportunities'],
  'opportunities:read_assigned': ['crm', 'opportunities'],
  'opportunities:update_assigned': ['crm', 'opportunities'],
  'tasks:manage': ['crm', 'tasks'],
  'tasks:create_team': ['crm', 'tasks'],
  'tasks:update_team': ['crm', 'tasks'],
  'tasks:read_assigned': ['crm', 'tasks'],
  'tasks:update_assigned': ['crm', 'tasks'],
  'notes:manage': ['crm'],
  'notes:create_team': ['crm'],
  'notes:create_assigned': ['crm'],
  'followups:manage_assigned': ['crm', 'contacts'],
  'conversations:manage': ['conversations', 'inbox'],
  'conversations:read': ['conversations', 'inbox'],
  'conversations:assign': ['conversations', 'inbox'],
  'conversations:send': ['conversations', 'inbox'],
  'conversations:close': ['conversations', 'inbox'],
  'conversations:read_team': ['conversations', 'inbox'],
  'conversations:assign_team': ['conversations', 'inbox'],
  'conversations:send_team': ['conversations', 'inbox'],
  'conversations:close_team': ['conversations', 'inbox'],
  'conversations:read_assigned': ['conversations', 'inbox'],
  'conversations:send_assigned': ['conversations', 'inbox'],
  'conversations:internal_notes': ['conversations', 'inbox'],
  'channel_configs:manage': ['conversations', 'inbox'],
  'whatsapp_connections:read': ['conversations', 'inbox', 'whatsapp'],
  'whatsapp_sessions:create': ['conversations', 'inbox', 'whatsapp'],
  'whatsapp_sessions:view_qr': ['conversations', 'inbox', 'whatsapp'],
  'whatsapp_sessions:reconnect': ['conversations', 'inbox', 'whatsapp'],
  'whatsapp_sessions:disconnect': ['conversations', 'inbox', 'whatsapp'],
  'whatsapp_sessions:delete_auth': ['conversations', 'inbox', 'whatsapp'],
  'whatsapp_sessions:diagnostics': ['conversations', 'inbox', 'whatsapp'],
  'whatsapp_sessions:manage_companies': ['conversations', 'inbox', 'whatsapp'],
  'whatsapp_messages:send': ['conversations', 'inbox', 'whatsapp'],
  'whatsapp_provider:select': ['conversations', 'inbox', 'whatsapp'],
  'message_templates:manage': ['conversations', 'inbox'],
  'message_templates:read': ['conversations', 'inbox'],
  'message_templates:use': ['conversations', 'inbox'],
  'routing_rules:manage': ['conversations', 'inbox'],
  'routing_rules:read': ['conversations', 'inbox'],
  'notifications:read': ['notifications'],
  'consent:read': ['crm', 'contacts'],
  'consent:manage': ['crm', 'contacts'],
  'consent:override': ['conversations', 'inbox'],
  'consent:export': ['crm', 'contacts'],
  'dnd:read': ['crm', 'contacts'],
  'dnd:manage': ['crm', 'contacts'],
  'suppressions:manage': ['conversations', 'inbox'],
  'quiet_hours:manage': ['conversations', 'inbox'],
  'message_diagnostics:read': ['conversations', 'inbox'],
  'messages:send_commercial': ['conversations', 'inbox'],
  'messages:send_transactional': ['conversations', 'inbox'],
  'communication_reports:read': ['conversations', 'inbox', 'reporting'],
  'consent:read_team': ['crm', 'contacts'],
  'consent:manage_team': ['crm', 'contacts'],
  'dnd:read_team': ['crm', 'contacts'],
  'dnd:manage_team': ['crm', 'contacts'],
  'message_diagnostics:read_team': ['conversations', 'inbox'],
  'communication_reports:read_team': ['conversations', 'inbox', 'reporting'],
  'consent:read_assigned': ['crm', 'contacts'],
  'consent:record_assigned': ['crm', 'contacts'],
  'dnd:read_assigned': ['crm', 'contacts'],
  'communication_preferences:update_assigned': ['crm', 'contacts'],
  'message_diagnostics:read_assigned': ['conversations', 'inbox'],
  'media:read': ['media'],
  'media:upload': ['media'],
  'media:read_team': ['media'],
  'media:upload_team': ['media'],
  'media:read_assigned': ['media'],
  'media:upload_assigned': ['media'],
  'calendars:manage': ['calendar'],
  'calendars:read_team': ['calendar'],
  'calendars:read_assigned': ['calendar'],
  'appointments:manage': ['calendar'],
  'appointments:manage_team': ['calendar'],
  'appointments:read_team': ['calendar'],
  'appointments:update_team': ['calendar'],
  'appointment_analytics:read': ['calendar'],
  'appointment_analytics:read_team': ['calendar'],
  'appointment_analytics:read_assigned': ['calendar'],
  'appointments:manage_assigned': ['calendar'],
  'appointments:read_assigned': ['calendar'],
  'appointments:update_assigned': ['calendar'],
  'booking_links:manage': ['calendar', 'bookings'],
  'availability:manage': ['calendar'],
  'availability:read_team': ['calendar'],
  'calendar_profiles:apply': ['calendar'],
  'workflows:read': ['automations', 'workflows'],
  'workflows:manage': ['automations', 'workflows'],
  'workflows:test': ['automations', 'workflows'],
  'workflows:read_team': ['automations', 'workflows'],
  'workflow_runs:read': ['automations', 'workflows'],
  'workflow_runs:read_team': ['automations', 'workflows'],
  'forms:manage': ['forms'],
  'forms:read': ['forms'],
  'forms:submissions': ['forms'],
  'forms:analytics': ['forms'],
  'forms:read_team': ['forms'],
  'forms:submissions_read': ['forms'],
  'landing_pages:manage': ['landing_pages'],
  'landing_pages:analytics': ['landing_pages'],
  'funnels:manage': ['funnels'],
  'funnels:analytics': ['funnels'],
  'funnels:read_team': ['funnels'],
  'campaigns:manage': ['forms'],
  'campaigns:read': ['forms'],
  'campaigns:read_team': ['forms'],
  'integrations:manage': ['integrations'],
  'integrations:read': ['integrations'],
  'integrations:read_team': ['integrations'],
  'integrations:events': ['integrations'],
  'attribution:read': ['crm'],
  'attribution:read_team': ['crm'],
  'attribution:read_assigned': ['crm'],
  'marketing_reports:read': ['forms', 'reporting'],
  'marketing_reports:read_team': ['forms', 'reporting'],
  'reputation:manage': ['reputation'],
  'reputation:analytics': ['reputation'],
  'reviews:manage': ['reputation', 'reviews'],
  'reviews:read_team': ['reputation', 'reviews'],
  'reviews:read_assigned': ['reputation', 'reviews'],
  'review_requests:manage': ['reputation', 'reviews'],
  'review_requests:create_team': ['reputation', 'reviews'],
  'review_requests:create_assigned': ['reputation', 'reviews'],
  'testimonials:manage': ['reputation', 'testimonials'],
  'review_widgets:manage': ['reputation', 'reviews'],
  'surveys:manage': ['reputation', 'surveys'],
  'coupons:manage': ['loyalty', 'coupons'],
  'coupons:issue_team': ['loyalty', 'coupons'],
  'coupons:issue_assigned': ['loyalty', 'coupons'],
  'referrals:manage': ['loyalty', 'referrals'],
  'referrals:read_team': ['loyalty', 'referrals']
};

export function permissionModules(permission) {
  return PERMISSION_MODULES[permission] || [];
}

export function permissionsAllowedForRole(role, permissions) {
  const rolePermissions = new Set(ROLE_PERMISSIONS[role] || []);
  return [...new Set(permissions)].filter((permission) => rolePermissions.has(permission));
}

export function filterPermissionsByModules(permissions, enabledModules) {
  const modules = new Set(enabledModules);
  return permissions.filter((permission) =>
    permissionModules(permission).every((moduleKey) => modules.has(moduleKey))
  );
}

export function getPermissionTemplate(key) {
  return PERMISSION_TEMPLATES.find((template) => template.key === key) || null;
}
